### ISSUE TITLE
Could not resolve project :core

### ISSUE THREAD

**Issue by jbalves** [danilosoarespinheiro/memory-note-clean-solid#3]
FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':app:compileDebugJavaWithJavac'.
> Could not resolve all task dependencies for configuration ':app:debugCompileClasspath'.
   > Could not resolve project :core.
     Required by:
         project :app
      > No matching configuration of project :core was found. The consumer was configured to find an API of a component, preferably optimized for Android, as well as attribute 'com.android.build.api.attributes.BuildTypeAttr' with value 'debug', attribute 'com.android.build.api.attributes.AgpVersionAttr' with value '7.4.2', attribute 'org.jetbrains.kotlin.platform.type' with value 'androidJvm' but:
          - None of the consumable configurations have attributes

**Comment by danilosoarespinheiro** [comment]
Closed on 86c15d0
